# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {J:/ECEN 220 Labs/Lab_3-Structural_System_Verilog/Lab_3-Structural_System_Verilog.cache/wt} [current_project]
set_property parent.project_path {J:/ECEN 220 Labs/Lab_3-Structural_System_Verilog/Lab_3-Structural_System_Verilog.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {j:/ECEN 220 Labs/Lab_3-Structural_System_Verilog/Lab_3-Structural_System_Verilog.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {{J:/ECEN 220 Labs/Lab_3-Structural_System_Verilog/Lab_3-Structural_System_Verilog.srcs/sources_1/imports/ECEN 220 Labs/FourFunctions.sv.txt}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{J:/ECEN 220 Labs/Lab_3-Structural_System_Verilog/Lab_3-Structural_System_Verilog.srcs/constrs_1/new/Testxdc.xdc}}
set_property used_in_implementation false [get_files {{J:/ECEN 220 Labs/Lab_3-Structural_System_Verilog/Lab_3-Structural_System_Verilog.srcs/constrs_1/new/Testxdc.xdc}}]


synth_design -top FourFunctions -part xc7a100tcsg324-1


write_checkpoint -force -noxdef FourFunctions.dcp

catch { report_utilization -file FourFunctions_utilization_synth.rpt -pb FourFunctions_utilization_synth.pb }
