# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {J:/ECEN 220 Labs/Lab9_PulseWidthModulation/Lab9_PulseWidthModulation.cache/wt} [current_project]
set_property parent.project_path {J:/ECEN 220 Labs/Lab9_PulseWidthModulation/Lab9_PulseWidthModulation.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {j:/ECEN 220 Labs/Lab9_PulseWidthModulation/Lab9_PulseWidthModulation.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {J:/ECEN 220 Labs/Lab9_PulseWidthModulation/Lab9_PulseWidthModulation.srcs/sources_1/new/PWM.sv}
  {J:/ECEN 220 Labs/Lab9_PulseWidthModulation/Lab9_PulseWidthModulation.srcs/sources_1/imports/new/SevenSegmentControl.sv}
  {J:/ECEN 220 Labs/Lab9_PulseWidthModulation/Lab9_PulseWidthModulation.srcs/sources_1/new/PWM_top.sv}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{J:/ECEN 220 Labs/Lab9_PulseWidthModulation/Lab9_PulseWidthModulation.srcs/constrs_1/imports/Lab9_PulseWidthModulation/nexys4_220.xdc}}
set_property used_in_implementation false [get_files {{J:/ECEN 220 Labs/Lab9_PulseWidthModulation/Lab9_PulseWidthModulation.srcs/constrs_1/imports/Lab9_PulseWidthModulation/nexys4_220.xdc}}]


synth_design -top PWM_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef PWM_top.dcp

catch { report_utilization -file PWM_top_utilization_synth.rpt -pb PWM_top_utilization_synth.pb }
